version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/wallet
    depends_on:
      - "db"
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:z
